### ISSUE TITLE
Present Windows indicator in Plasma 5

### ISSUE THREAD

**Issue by eeque** [obnosim/velours#1] opened 2015-08-31 13:29 UTC
Hello. Love your work.

The blue "glow" that shows up as a hint when there a screen edge action set is replaced by a White / black bar that looks... well, glitched. I'm not sure if this is a design decision.
I'm attaching an image that shows the bar over a window at the Top Left corner of my screen as set for the Present Windows effect.

![indicator](https://cloud.githubusercontent.com/assets/2138140/9579718/3b34ad12-5012-11e5-9e46-547246a350aa.png)

**Comment by obnosim** [comment] 2015-09-01 23:37
If it's about the design, it is a design decision, although I'll concede it's poor. The problem is that both screen edges and hidden panels use those elements in an inconsistent way (sometimes scaled, sometimes not) and it's hard to find a design that works all the time. I made something up a while ago and forgot about it. I'll try to find something better in the next few days. In the meantime, if you'd rather use the default glow, you can rename ~/.local/share/plasma/desktoptheme/velours/widgets/glowbar.svg to something else or just delete it.

If it's about how it just cuts off, it might be a bug.

Thanks for letting me know!

**Comment by obnosim** [comment] 2015-09-01 23:58
Update: the right element was incorrectly named and the bottomright one was unnamed. This is fixed in both branches now. A design overhaul will follow soon.

**Comment by obnosim** [comment] 2015-09-05 00:54
![Screenshot](http://i.imgur.com/KCfJr2r.png)
There! I found a way that should look good for both screen edges and hot corners and integrate better with the rest of the theme. Both branches have the new file and the packages will be updated soon.

**Closed by obnosim** 2015-09-05 00:54 UTC
Labels: bug, enhancement
